version: '3.6'
services:
  # Create registry container instance
  nmos-registry:
    image: rhastie/nmos-cpp:latest
    container_name: nmos-registry
    hostname: nmos-registry
    ports:
    - "8010-8011:8010-8011"
    - "1883:1883"
    volumes:
    - "./registry.json:/home/registry.json"
    environment:
    - RUN_NODE=FALSE
    networks: 
      private-nmos:
        ipv4_address: '172.30.101.3'
      external:
        ipv4_address: '192.168.6.101'

  # Create node container instance
  nmos-virtnode:
    image: rhastie/nmos-cpp:latest
    container_name: nmos-virtnode
    hostname: nmos-virtnode
    ports:
    - "11000-11001:11000-11001"
    volumes:
    - "./node.json:/home/node.json"
    environment:
    - RUN_NODE=TRUE
    networks:
      private-nmos:
        ipv4_address: '172.30.101.4'
      external:
        ipv4_address: '192.168.6.102'
    depends_on:
    - nmos-registry    

  # Create AMWA-TV NMOS Testing container instance
  nmos-testing:
    image: amwa/nmos-testing
    container_name: nmos-testing
    hostname: nmos-testing
    entrypoint: |
      /bin/sh -c "apk add avahi; 
      sed -i 's/#enable-dbus=yes/enable-dbus=no/g' /etc/avahi/avahi-daemon.conf;
      avahi-daemon -D;
      python3 nmos-test.py"
    ports:
    - "5000:5000"
    volumes:
    - "./Config.py:/config/Config.py"
    networks:
      private-nmos:
        ipv4_address: '172.30.101.5'
      external:
        ipv4_address: '192.168.6.103'
    depends_on:
    - nmos-virtnode


networks:
    private-nmos:
        # Create private network for inter-comtainer NMOS communications
        driver: bridge
        ipam:
            config:
            - subnet: 172.30.101.1/24

    external:
        driver: macvlan
        driver_opts:
            parent: ens33
        ipam:
            config:
            - subnet: 192.168.6.1/24
